// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb/abi-mq-pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SendTask) Reset() {
	*x = SendTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTask) ProtoMessage() {}

func (x *SendTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTask.ProtoReflect.Descriptor instead.
func (*SendTask) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{0}
}

func (x *SendTask) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendTask) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{1}
}

func (x *SendResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *SendResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

func (x *SendResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueueCreateTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
}

func (x *QueueCreateTask) Reset() {
	*x = QueueCreateTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueCreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueCreateTask) ProtoMessage() {}

func (x *QueueCreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueCreateTask.ProtoReflect.Descriptor instead.
func (*QueueCreateTask) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{2}
}

func (x *QueueCreateTask) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QueueCreateTask) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type QueueCreateResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *QueueCreateResult) Reset() {
	*x = QueueCreateResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueCreateResult) ProtoMessage() {}

func (x *QueueCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueCreateResult.ProtoReflect.Descriptor instead.
func (*QueueCreateResult) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{3}
}

func (x *QueueCreateResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *QueueCreateResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type QueueRemoveTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Queue string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
}

func (x *QueueRemoveTask) Reset() {
	*x = QueueRemoveTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueRemoveTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveTask) ProtoMessage() {}

func (x *QueueRemoveTask) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveTask.ProtoReflect.Descriptor instead.
func (*QueueRemoveTask) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{4}
}

func (x *QueueRemoveTask) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QueueRemoveTask) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type QueueRemoveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  int32  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *QueueRemoveResult) Reset() {
	*x = QueueRemoveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_abi_mq_pb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueRemoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveResult) ProtoMessage() {}

func (x *QueueRemoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_abi_mq_pb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveResult.ProtoReflect.Descriptor instead.
func (*QueueRemoveResult) Descriptor() ([]byte, []int) {
	return file_pb_abi_mq_pb_proto_rawDescGZIP(), []int{5}
}

func (x *QueueRemoveResult) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *QueueRemoveResult) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

var File_pb_abi_mq_pb_proto protoreflect.FileDescriptor

var file_pb_abi_mq_pb_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x61, 0x62, 0x69, 0x2d, 0x6d, 0x71, 0x2d, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6d, 0x71, 0x22, 0x34, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x4a,
	0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x0f, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x3d, 0x0a, 0x0f,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x32, 0xa5,
	0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x6d, 0x71, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x73, 0x6b,
	0x1a, 0x0e, 0x2e, 0x6d, 0x71, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x39, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x13, 0x2e, 0x6d, 0x71, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x1a, 0x15, 0x2e, 0x6d, 0x71, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x0b, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x71, 0x2e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x1a,
	0x15, 0x2e, 0x6d, 0x71, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_abi_mq_pb_proto_rawDescOnce sync.Once
	file_pb_abi_mq_pb_proto_rawDescData = file_pb_abi_mq_pb_proto_rawDesc
)

func file_pb_abi_mq_pb_proto_rawDescGZIP() []byte {
	file_pb_abi_mq_pb_proto_rawDescOnce.Do(func() {
		file_pb_abi_mq_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_abi_mq_pb_proto_rawDescData)
	})
	return file_pb_abi_mq_pb_proto_rawDescData
}

var file_pb_abi_mq_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_abi_mq_pb_proto_goTypes = []interface{}{
	(*SendTask)(nil),          // 0: mq.SendTask
	(*SendResult)(nil),        // 1: mq.SendResult
	(*QueueCreateTask)(nil),   // 2: mq.QueueCreateTask
	(*QueueCreateResult)(nil), // 3: mq.QueueCreateResult
	(*QueueRemoveTask)(nil),   // 4: mq.QueueRemoveTask
	(*QueueRemoveResult)(nil), // 5: mq.QueueRemoveResult
}
var file_pb_abi_mq_pb_proto_depIdxs = []int32{
	0, // 0: mq.Service.Send:input_type -> mq.SendTask
	2, // 1: mq.Service.QueueCreate:input_type -> mq.QueueCreateTask
	4, // 2: mq.Service.QueueRemove:input_type -> mq.QueueRemoveTask
	1, // 3: mq.Service.Send:output_type -> mq.SendResult
	3, // 4: mq.Service.QueueCreate:output_type -> mq.QueueCreateResult
	5, // 5: mq.Service.QueueRemove:output_type -> mq.QueueRemoveResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_abi_mq_pb_proto_init() }
func file_pb_abi_mq_pb_proto_init() {
	if File_pb_abi_mq_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_abi_mq_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_abi_mq_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_abi_mq_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueCreateTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_abi_mq_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueCreateResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_abi_mq_pb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueRemoveTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_abi_mq_pb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueRemoveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_abi_mq_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_abi_mq_pb_proto_goTypes,
		DependencyIndexes: file_pb_abi_mq_pb_proto_depIdxs,
		MessageInfos:      file_pb_abi_mq_pb_proto_msgTypes,
	}.Build()
	File_pb_abi_mq_pb_proto = out.File
	file_pb_abi_mq_pb_proto_rawDesc = nil
	file_pb_abi_mq_pb_proto_goTypes = nil
	file_pb_abi_mq_pb_proto_depIdxs = nil
}
