// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb/abi-mq-pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Send(ctx context.Context, in *SendTask, opts ...grpc.CallOption) (*SendResult, error)
	QueueCreate(ctx context.Context, in *QueueCreateTask, opts ...grpc.CallOption) (*QueueCreateResult, error)
	QueueRemove(ctx context.Context, in *QueueRemoveTask, opts ...grpc.CallOption) (*QueueRemoveResult, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Send(ctx context.Context, in *SendTask, opts ...grpc.CallOption) (*SendResult, error) {
	out := new(SendResult)
	err := c.cc.Invoke(ctx, "/mq.Service/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) QueueCreate(ctx context.Context, in *QueueCreateTask, opts ...grpc.CallOption) (*QueueCreateResult, error) {
	out := new(QueueCreateResult)
	err := c.cc.Invoke(ctx, "/mq.Service/QueueCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) QueueRemove(ctx context.Context, in *QueueRemoveTask, opts ...grpc.CallOption) (*QueueRemoveResult, error) {
	out := new(QueueRemoveResult)
	err := c.cc.Invoke(ctx, "/mq.Service/QueueRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	Send(context.Context, *SendTask) (*SendResult, error)
	QueueCreate(context.Context, *QueueCreateTask) (*QueueCreateResult, error)
	QueueRemove(context.Context, *QueueRemoveTask) (*QueueRemoveResult, error)
}

// UnimplementedServiceServer should be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Send(context.Context, *SendTask) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedServiceServer) QueueCreate(context.Context, *QueueCreateTask) (*QueueCreateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueCreate not implemented")
}
func (UnimplementedServiceServer) QueueRemove(context.Context, *QueueRemoveTask) (*QueueRemoveResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueRemove not implemented")
}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mq.Service/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Send(ctx, req.(*SendTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_QueueCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).QueueCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mq.Service/QueueCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).QueueCreate(ctx, req.(*QueueCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_QueueRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRemoveTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).QueueRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mq.Service/QueueRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).QueueRemove(ctx, req.(*QueueRemoveTask))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Service_Send_Handler,
		},
		{
			MethodName: "QueueCreate",
			Handler:    _Service_QueueCreate_Handler,
		},
		{
			MethodName: "QueueRemove",
			Handler:    _Service_QueueRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/abi-mq-pb.proto",
}
